spring.application.name=nori-stock
spring.datasource.url=jdbc:postgresql://localhost:5432/nori_stock
spring.datasource.username=postgres
spring.datasource.password=nori@2026
server.port=8081
server.servlet.context-path=/nori-stock
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
