spring.application.name=nori-stock
spring.datasource.url=jdbc:postgresql://localhost:5432/nori_stock
spring.datasource.username=postgres
spring.datasource.password=nori@2026
server.port=8081
server.servlet.context-path=/nori-stock
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
api.security.token.secret=7nq2CoNNELbAOXuDbt0fao24jKfZPhOuRodc6rKIHqE=
#1 hour
api.security.token.expiration=3600000
